/*
 //  Problem12.c
 //  Project Euler
 //
 //  Created by Denis Meyer on 3/28/11.
 //  Copyright 2011 CallToPower Software. All rights reserved.
 */

/*
 Problem
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.
 What is the value of the first triangle number to have over five hundred divisors?
 => 76576500
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

#define MIN_DIVISORS 500

/*
 Halt divisions when the divisor exceeds the square root of the triangle number.
 For every exact divisor up to the square root, there is a corresponding divisor above the square root.
 */
void print_solution()
{
    int i;
    long long t, cnt, a, ttx;
    
    t=1; // triangle number
    a=1;
    cnt=0;
    while(cnt < MIN_DIVISORS)
    {
        cnt = 0;
        a += 1;
        t += a;
        ttx = sqrt(t);
        for (i = 1; i <= ttx; i++)
        {
            if(t%i==0)
            {
                cnt += 2;
            }
            if(t == pow(ttx, 2))
            {
                --cnt; // correction for a perfect square
            }
        }
    }
    printf("%lld", t);
}

int main (int argc, const char * argv[])
{
    double start, end;
    start = clock();
    print_solution();
    end = clock();
    printf("\nprogram execution time: %fs\n\n", (((double) (end - start)) / CLOCKS_PER_SEC));
    return 0;
}
