/*
 //  Problem2.c
 //  Project Euler
 //
 //  Created by Denis Meyer on 3/27/11.
 //  Copyright 2011 CallToPower Software. All rights reserved.
 */

/*
 Problem
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 => 4613732
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define LIM 4000000l

long get_fib()
{
    long last2, last1, curr, even;
    last2 = 0;
    last1 = 0;
    curr = 1;
    even = 0;
    while(curr < LIM)
    {
        last2 = last1;
        last1 = curr;
        curr = last2 + last1;
        if(curr%2==0)
        {
            even += curr;
        }
    }
    return even;
}

void print_solution()
{
    printf("First Fibonacci number after %ld: %ld\n", LIM, get_fib());
}

int main (int argc, const char * argv[])
{
    double start, end;
    start = clock();
    print_solution();
    end = clock();
    printf("\nprogram execution time: %fs\n\n", (((double) (end - start)) / CLOCKS_PER_SEC));
    return 0;
}
